name: "HomeWizard P1 Emulator"
description: "Emulates a HomeWizard P1 meter using Home Assistant sensors to feed data into devices like Zendure SolarFlow."
version: "1.0.5"
slug: "homewizard_p1_emulator"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
host_network: true
homeassistant_api: true
hassio_api: true
options:
  debug_mode: true
  import_t1: "sensor.p1_energy_consumed_tariff_1"
  import_t2: "sensor.p1_energy_consumed_tariff_2"
  export_t1: "sensor.p1_energy_produced_tariff_1"
  export_t2: "sensor.p1_energy_produced_tariff_2"
  active_power_consumed: "sensor.p1_power_consumed"
  active_power_produced: "sensor.p1_power_produced"
schema:
  debug_mode: bool
  device_serial: str?
  import_t1: str?
  import_t2: str?
  import_t3: str?
  import_t4: str?
  export_t1: str?
  export_t2: str?
  export_t3: str?
  export_t4: str?
  active_power_consumed: str?
  active_power_produced: str?
  power_l1: str?
  power_l2: str?
  power_l3: str?
  voltage_l1: str?
  voltage_l2: str?
  voltage_l3: str?
  current_l1: str?
  current_l2: str?
  current_l3: str?
  short_power_drop: str?
  power_fail: str?