name: "HomeWizard P1 Emulator"
description: "Emulates a HomeWizard P1 meter using Home Assistant sensors to feed data into devices like Zendure SolarFlow."
version: "1.0.2"
slug: "homewizard_p1_emulator"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
host_network: true
homeassistant_api: true
hassio_api: true
options:
  debug_mode: true
  import_t1: ""
  import_t2: ""
  active_power_consumed: ""
schema:
  debug_mode: bool
  device_serial: str?
  import_t1: "sensor?"
  import_t2: "sensor?"
  export_t1: "sensor?"
  export_t2: "sensor?"
  active_power_consumed: "sensor?"
  active_power_produced: "sensor?"
  power_l1: "sensor?"
  power_l2: "sensor?"
  power_l3: "sensor?"
  voltage_l1: "sensor?"
  voltage_l2: "sensor?"
  voltage_l3: "sensor?"
  current_l1: "sensor?"
  current_l2: "sensor?"
  current_l3: "sensor?"
  short_power_drop: "binary_sensor?"
  power_fail: "binary_sensor?"